export { default as About } from './About.svelte'
export { default as HeadingExtra } from './HeadingExtra.svelte'
export { default as HeadingLink } from './HeadingLink.svelte'
export { default as HeadingUnderline } from './HeadingUnderline.svelte'
export { default as Projects } from './Projects.svelte'
export { default as Socials } from './Socials.svelte'
export { default as Team } from './Team.svelte'
